// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "bbd2e31b-2cd6-474d-96af-e87580cc890a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1661491104);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1661490932);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1661491075);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{0d424225-d25f-40dd-a603-fadcd41cb628}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1661490927);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f712a61c-ba10-419f-a853-648da33ee655}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1661490929);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1661491106939");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1661492926939");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1661490933411");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1661512533411");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220822144605");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220822144605");
user_pref("browser.startup.homepage_override.mstone", "104.0");
user_pref("browser.startup.lastColdStartupCheck", 1661491075);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1661490929857");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "104.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "VN");
user_pref("dom.push.userAgentID", "7b98a0fa3a40441cb0673fc8b6d3686c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220822144605");
user_pref("extensions.lastAppVersion", "104.0");
user_pref("extensions.lastPlatformVersion", "104.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"db74cc6c-c96b-49b6-a06b-54c544fd8dc2\",\"formautofill@mozilla.org\":\"55e1bad5-d68d-40d4-8908-57c71874b325\",\"pictureinpicture@mozilla.org\":\"ed85d83d-d5c4-4797-9718-72d311eabe6b\",\"screenshots@mozilla.org\":\"23e2209a-8e47-469c-ae5b-d3540ff0df6a\",\"webcompat-reporter@mozilla.org\":\"af01e330-52be-400a-8224-351126290077\",\"webcompat@mozilla.org\":\"f06cb725-09f3-44d4-a350-e6ecdfb9a7a0\",\"default-theme@mozilla.org\":\"dfe9ffd7-8ff1-4712-8478-e5f3e3c24554\",\"addons-search-detection@mozilla.com\":\"4bc37181-0c7a-42cc-8349-41636fabb8d8\",\"google@search.mozilla.org\":\"675a623f-bfb8-47d7-8bd8-f625ca96a32a\",\"amazondotcom@search.mozilla.org\":\"69c0eee7-65af-455e-bc8f-26bcecc53cde\",\"wikipedia@search.mozilla.org\":\"973c4662-97ef-4dfc-b2fa-4bccd04bbdd8\",\"bing@search.mozilla.org\":\"f312617d-ba57-48d2-85b5-d0e48051cf8f\",\"ddg@search.mozilla.org\":\"3a661c89-bffe-408f-9c8a-a579d8d7eae4\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1661490931);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-50-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"d5705562-a616-454f-b96f-a07127c648d3\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 50% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-08-26T05:15:30.201Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1b07facf-cd02-4c5a-8867-0b51bf4dc9ec");
user_pref("toolkit.startup.last_success", 1661491073);
user_pref("toolkit.telemetry.cachedClientID", "526ea4e1-f12e-47a0-b353-cbb43ac4020e");
user_pref("toolkit.telemetry.previousBuildID", "20220822144605");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
